// Generated by tools/generate_plan.py. Edit the generator (or this file) and bump version.
window.PLAN = {
 "version": "2026-09-26.1",
 "start": "2026-10-01",
 "end": "2026-12-31",
 "weekend": [
  4,
  5
 ],
 "profiles": [
  {
   "id": "ahmed",
   "name": "Ahmed"
  },
  {
   "id": "bassant",
   "name": "Bassant"
  }
 ],
 "weeks": [
  {
   "n": 1,
   "title": "Python revision",
   "start": "2026-10-01",
   "end": "2026-10-07"
  },
  {
   "n": 2,
   "title": "OOP (Days 1–4) + Cosmic Python 1–2",
   "start": "2026-10-08",
   "end": "2026-10-14"
  },
  {
   "n": 3,
   "title": "OOP Day 5 + Backend (Days 1–3) + Cosmic 3",
   "start": "2026-10-15",
   "end": "2026-10-21"
  },
  {
   "n": 4,
   "title": "Backend (Days 4–7) + Cosmic 4",
   "start": "2026-10-22",
   "end": "2026-10-28"
  },
  {
   "n": 5,
   "title": "Databases + SQL (Days 1–4) + Cosmic 5",
   "start": "2026-10-29",
   "end": "2026-11-04"
  },
  {
   "n": 6,
   "title": "PostgreSQL + Indexes + Month review",
   "start": "2026-11-05",
   "end": "2026-11-11"
  },
  {
   "n": 7,
   "title": "Text, Embeddings & Transformers + Cosmic 6–7",
   "start": "2026-11-12",
   "end": "2026-11-24"
  },
  {
   "n": 8,
   "title": "LLMs",
   "start": "2026-11-25",
   "end": "2026-12-03"
  },
  {
   "n": 9,
   "title": "Prompt engineering + Agent book 1–2",
   "start": "2026-12-04",
   "end": "2026-12-10"
  },
  {
   "n": 10,
   "title": "Advanced RAG + Vector DBs + RAG research guide",
   "start": "2026-12-11",
   "end": "2026-12-23"
  },
  {
   "n": 11,
   "title": "AI Agents: fundamentals + Agent book 3–4",
   "start": "2026-12-24",
   "end": "2026-12-31"
  }
 ],
 "days": [
  {
   "date": "2026-10-01",
   "week": 1,
   "tasks": [
    {
     "id": "t0011",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0001",
     "title": "Python core: data types, collections, mutability, == vs is, copy",
     "hours": 1.5,
     "type": "study",
     "details": "Shallow vs deep copy, hashable keys, what happens when you pass a list to a function.",
     "link": ""
    },
    {
     "id": "t0018",
     "title": "Beyond the Basics, video 1 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-02",
   "week": 1,
   "tasks": [
    {
     "id": "t0012",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0002",
     "title": "Task: User/Task Data Processor",
     "hours": 2,
     "type": "project",
     "details": "Unique skills with a set, deep copy for nested settings, modify a copy safely.",
     "link": ""
    },
    {
     "id": "t0003",
     "title": "Functions, *args/**kwargs, lambda, map/filter, comprehensions",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0019",
     "title": "System Design playlist, video 1 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-03",
   "week": 1,
   "tasks": [
    {
     "id": "t0013",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0004",
     "title": "Task: Employee Data Processor",
     "hours": 2,
     "type": "project",
     "details": "calculate_salary(*salaries, bonus=0), group_by_department, map/filter/lambda.",
     "link": ""
    },
    {
     "id": "t0005",
     "title": "Iterators, generators, decorators, context managers, exceptions",
     "hours": 1.5,
     "type": "study",
     "details": "The most important day for understanding how Python works.",
     "link": ""
    },
    {
     "id": "t0020",
     "title": "Beyond the Basics, video 2 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-04",
   "week": 1,
   "tasks": [
    {
     "id": "t0014",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0006",
     "title": "Project: Log Processing System",
     "hours": 2,
     "type": "project",
     "details": "LogIterator, error_logs() generator, @measure_time, @handle_errors, log_file() context manager, custom exceptions.",
     "link": ""
    },
    {
     "id": "t0021",
     "title": "System Design playlist, video 2 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-05",
   "week": 1,
   "tasks": [
    {
     "id": "t0015",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0007",
     "title": "Modules, packages, venv, type hints, dataclasses, Pydantic",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0008",
     "title": "Project: API Request Validation Package",
     "hours": 2,
     "type": "project",
     "details": "user_service package, dataclass User, Pydantic CreateUserRequest, absolute vs relative imports.",
     "link": ""
    },
    {
     "id": "t0022",
     "title": "Beyond the Basics, video 3 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-06",
   "week": 1,
   "tasks": [
    {
     "id": "t0016",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0009",
     "title": "Async/await, threads, processes, CPU vs I/O bound",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0023",
     "title": "System Design playlist, video 3 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-07",
   "week": 1,
   "tasks": [
    {
     "id": "t0017",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0010",
     "title": "Project: Concurrent Fetcher → Mini Async Job Processing System",
     "hours": 2,
     "type": "project",
     "details": "Sequential vs asyncio.gather, then combine everything with @measure_time. Review the interview questions list.",
     "link": ""
    },
    {
     "id": "t0024",
     "title": "Beyond the Basics, video 4 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-08",
   "week": 2,
   "tasks": [
    {
     "id": "t0036",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0025",
     "title": "OOP from zero: classes, objects, attributes, instance/class/static methods",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0026",
     "title": "Project: Bank Account System",
     "hours": 1.5,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0043",
     "title": "Beyond the Basics, video 5 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-09",
   "week": 2,
   "tasks": [
    {
     "id": "t0037",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0027",
     "title": "Four pillars: encapsulation, inheritance, polymorphism, abstraction + composition",
     "hours": 2,
     "type": "study",
     "details": "@property, super(), ABC, IS-A vs HAS-A.",
     "link": ""
    },
    {
     "id": "t0044",
     "title": "System Design playlist, video 4 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-10",
   "week": 2,
   "tasks": [
    {
     "id": "t0038",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0028",
     "title": "Project: E-commerce Domain (PaymentProvider → Stripe/Paymob)",
     "hours": 2,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0029",
     "title": "Cosmic Python ch. 1: Domain Modeling",
     "hours": 1.25,
     "type": "book",
     "details": "",
     "link": "https://www.cosmicpython.com/book/preface.html"
    },
    {
     "id": "t0045",
     "title": "Beyond the Basics, video 6 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-11",
   "week": 2,
   "tasks": [
    {
     "id": "t0039",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0030",
     "title": "Advanced Python OOP: dunders, __eq__/__hash__, dataclasses, Protocol, DI",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0031",
     "title": "Project: Notification System (Email/SMS/Push)",
     "hours": 2,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0046",
     "title": "System Design playlist, video 5 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-12",
   "week": 2,
   "tasks": [
    {
     "id": "t0040",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0032",
     "title": "Cosmic Python ch. 2: Repository Pattern",
     "hours": 1.25,
     "type": "book",
     "details": "",
     "link": "https://www.cosmicpython.com/book/preface.html"
    },
    {
     "id": "t0047",
     "title": "Beyond the Basics, video 7 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-13",
   "week": 2,
   "tasks": [
    {
     "id": "t0041",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0033",
     "title": "SOLID + key design patterns",
     "hours": 1.5,
     "type": "study",
     "details": "Factory, Builder, Adapter, Decorator, Facade, Strategy, Observer, Repository, Service Layer.",
     "link": ""
    },
    {
     "id": "t0034",
     "title": "Project: AI Model Provider System",
     "hours": 2,
     "type": "project",
     "details": "Swap OpenAIProvider for GeminiProvider without changing AIService.",
     "link": ""
    },
    {
     "id": "t0048",
     "title": "System Design playlist, video 6 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-14",
   "week": 2,
   "tasks": [
    {
     "id": "t0042",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0035",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0049",
     "title": "Beyond the Basics, video 8 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-15",
   "week": 3,
   "tasks": [
    {
     "id": "t0061",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0050",
     "title": "Production OOP: layers, OOP in Django/DRF/FastAPI, testing with fakes",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0068",
     "title": "Beyond the Basics, video 9 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-16",
   "week": 3,
   "tasks": [
    {
     "id": "t0062",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0051",
     "title": "Project: Mini RAG architecture with fake components",
     "hours": 2,
     "type": "project",
     "details": "FakeRetriever, FakeLLM, FakeVectorStore behind interfaces.",
     "link": ""
    },
    {
     "id": "t0052",
     "title": "Clean code (naming, functions, DRY/KISS/YAGNI) + Git",
     "hours": 1.25,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0053",
     "title": "Task: Refactor a messy API + Git branch/conflict/rebase practice",
     "hours": 1.25,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0069",
     "title": "System Design playlist, video 7 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-17",
   "week": 3,
   "tasks": [
    {
     "id": "t0063",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0054",
     "title": "Cosmic Python ch. 3: Coupling and Abstractions",
     "hours": 1.5,
     "type": "book",
     "details": "",
     "link": "https://www.cosmicpython.com/book/preface.html"
    },
    {
     "id": "t0055",
     "title": "HTTP, JSON, REST (methods, status codes, resource URLs)",
     "hours": 1.25,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0070",
     "title": "Beyond the Basics, video 10 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-18",
   "week": 3,
   "tasks": [
    {
     "id": "t0064",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0056",
     "title": "Project: Task Management REST API (FastAPI)",
     "hours": 2,
     "type": "project",
     "details": "CRUD, filtering, pagination.",
     "link": ""
    },
    {
     "id": "t0071",
     "title": "System Design playlist, video 8 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-19",
   "week": 3,
   "tasks": [
    {
     "id": "t0065",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0057",
     "title": "Authentication vs authorization: hashing, JWT, refresh tokens, RBAC",
     "hours": 1.25,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0058",
     "title": "Project: Add JWT auth + roles/permissions to the Task API",
     "hours": 2,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0072",
     "title": "Beyond the Basics, video 11 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-20",
   "week": 3,
   "tasks": [
    {
     "id": "t0066",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0059",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0073",
     "title": "System Design playlist, video 9 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-21",
   "week": 3,
   "tasks": [
    {
     "id": "t0067",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0060",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0074",
     "title": "Beyond the Basics, video 12 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-22",
   "week": 4,
   "tasks": [
    {
     "id": "t0085",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0075",
     "title": "Testing: pyramid, pytest, fixtures, parametrize, mocking",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0092",
     "title": "Beyond the Basics, video 13 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-23",
   "week": 4,
   "tasks": [
    {
     "id": "t0086",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0076",
     "title": "Project: Test the Task API (auth, permissions, CRUD, failure paths)",
     "hours": 2,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0077",
     "title": "Logging (structured, request IDs) + env vars + Pydantic Settings",
     "hours": 1,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0078",
     "title": "Project: Add .env config, logging, request IDs to the Task API",
     "hours": 1.5,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0093",
     "title": "System Design playlist, video 10 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-24",
   "week": 4,
   "tasks": [
    {
     "id": "t0087",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0079",
     "title": "Cosmic Python ch. 4: Service Layer",
     "hours": 1.5,
     "type": "book",
     "details": "",
     "link": "https://www.cosmicpython.com/book/preface.html"
    },
    {
     "id": "t0094",
     "title": "Beyond the Basics, video 14 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-25",
   "week": 4,
   "tasks": [
    {
     "id": "t0088",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0080",
     "title": "Design patterns: problem → pattern → trade-off",
     "hours": 2,
     "type": "study",
     "details": "Factory, Strategy, Adapter, Decorator, Facade, Observer, Repository, DI.",
     "link": ""
    },
    {
     "id": "t0081",
     "title": "Project: AI Provider Architecture (providers + retrievers)",
     "hours": 2.5,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0095",
     "title": "System Design playlist, video 11 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-26",
   "week": 4,
   "tasks": [
    {
     "id": "t0089",
     "title": "Kalamna work block (project week)",
     "hours": 2,
     "type": "kalamna",
     "details": "Build the production-style AI Support API capstone (Week 3 Day 7) inside Kalamna",
     "link": ""
    },
    {
     "id": "t0082",
     "title": "Review Weeks 1–4 checklists, fix weak spots",
     "hours": 2,
     "type": "review",
     "details": "",
     "link": ""
    },
    {
     "id": "t0096",
     "title": "Beyond the Basics, video 15 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-27",
   "week": 4,
   "tasks": [
    {
     "id": "t0090",
     "title": "Kalamna work block (project week)",
     "hours": 2,
     "type": "kalamna",
     "details": "Build the production-style AI Support API capstone (Week 3 Day 7) inside Kalamna",
     "link": ""
    },
    {
     "id": "t0083",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0097",
     "title": "System Design playlist, video 12 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-28",
   "week": 4,
   "tasks": [
    {
     "id": "t0091",
     "title": "Kalamna work block (project week)",
     "hours": 2,
     "type": "kalamna",
     "details": "Build the production-style AI Support API capstone (Week 3 Day 7) inside Kalamna",
     "link": ""
    },
    {
     "id": "t0084",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0098",
     "title": "Beyond the Basics, video 16 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-29",
   "week": 5,
   "tasks": [
    {
     "id": "t0111",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0099",
     "title": "SQL foundations: tables, keys, types, CRUD, filtering, sorting",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0100",
     "title": "LeetCode SQL: 5 problems (SELECT / filtering)",
     "hours": 1,
     "type": "leetcode",
     "details": "",
     "link": "https://leetcode.com/studyplan/top-sql-50/"
    },
    {
     "id": "t0118",
     "title": "Beyond the Basics, video 17 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-10-30",
   "week": 5,
   "tasks": [
    {
     "id": "t0112",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0101",
     "title": "DB design: relationships, constraints, normalization; build e-commerce schema",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0102",
     "title": "LeetCode SQL: 5 problems",
     "hours": 1,
     "type": "leetcode",
     "details": "",
     "link": "https://leetcode.com/studyplan/top-sql-50/"
    },
    {
     "id": "t0119",
     "title": "System Design playlist, video 13 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-10-31",
   "week": 5,
   "tasks": [
    {
     "id": "t0113",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0103",
     "title": "System Design Course, part 1 (first hour)",
     "hours": 1,
     "type": "video",
     "details": "",
     "link": "https://youtu.be/oYxTTirKY8M"
    },
    {
     "id": "t0104",
     "title": "Aggregation, GROUP BY, HAVING, all JOIN types",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0120",
     "title": "Beyond the Basics, video 18 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-01",
   "week": 5,
   "tasks": [
    {
     "id": "t0114",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0105",
     "title": "LeetCode SQL: 5 problems (JOIN / GROUP BY)",
     "hours": 1.25,
     "type": "leetcode",
     "details": "",
     "link": "https://leetcode.com/studyplan/top-sql-50/"
    },
    {
     "id": "t0106",
     "title": "Cosmic Python ch. 5: TDD in High and Low Gear",
     "hours": 1.5,
     "type": "book",
     "details": "",
     "link": "https://www.cosmicpython.com/book/preface.html"
    },
    {
     "id": "t0121",
     "title": "System Design playlist, video 14 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-02",
   "week": 5,
   "tasks": [
    {
     "id": "t0115",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0107",
     "title": "Subqueries, EXISTS, CTEs, window functions",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0108",
     "title": "LeetCode SQL: 5 problems (window functions)",
     "hours": 1.25,
     "type": "leetcode",
     "details": "",
     "link": "https://leetcode.com/studyplan/top-sql-50/"
    },
    {
     "id": "t0122",
     "title": "Beyond the Basics, video 19 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-03",
   "week": 5,
   "tasks": [
    {
     "id": "t0116",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0109",
     "title": "System Design Course, part 2 (second hour)",
     "hours": 1,
     "type": "video",
     "details": "",
     "link": "https://youtu.be/oYxTTirKY8M"
    },
    {
     "id": "t0123",
     "title": "System Design playlist, video 15 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-04",
   "week": 5,
   "tasks": [
    {
     "id": "t0117",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0110",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0124",
     "title": "Beyond the Basics, video 20 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-05",
   "week": 6,
   "tasks": [
    {
     "id": "t0136",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0125",
     "title": "PostgreSQL: UUID, JSONB, arrays, RETURNING, ON CONFLICT, transactions, ACID",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0143",
     "title": "Beyond the Basics, video 21 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-06",
   "week": 6,
   "tasks": [
    {
     "id": "t0137",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0126",
     "title": "LeetCode SQL: 5 problems",
     "hours": 1,
     "type": "leetcode",
     "details": "",
     "link": "https://leetcode.com/studyplan/top-sql-50/"
    },
    {
     "id": "t0127",
     "title": "Indexes: B-tree, composite, EXPLAIN / EXPLAIN ANALYZE",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0144",
     "title": "System Design playlist, video 16 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-07",
   "week": 6,
   "tasks": [
    {
     "id": "t0138",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0128",
     "title": "LeetCode SQL: 5 problems",
     "hours": 1,
     "type": "leetcode",
     "details": "",
     "link": "https://leetcode.com/studyplan/top-sql-50/"
    },
    {
     "id": "t0129",
     "title": "1 Million Requests per Second video, part 1",
     "hours": 1.25,
     "type": "video",
     "details": "",
     "link": "https://youtu.be/W4EwfEU8CGA"
    },
    {
     "id": "t0130",
     "title": "Django ORM bridge: select_related, prefetch_related, annotate, N+1",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0145",
     "title": "Beyond the Basics, video 22 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-08",
   "week": 6,
   "tasks": [
    {
     "id": "t0139",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0131",
     "title": "LeetCode SQL: 5 problems (35 total)",
     "hours": 1,
     "type": "leetcode",
     "details": "",
     "link": "https://leetcode.com/studyplan/top-sql-50/"
    },
    {
     "id": "t0132",
     "title": "1 Million Requests per Second video, part 2",
     "hours": 1.25,
     "type": "video",
     "details": "",
     "link": "https://youtu.be/W4EwfEU8CGA"
    },
    {
     "id": "t0146",
     "title": "System Design playlist, video 17 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-09",
   "week": 6,
   "tasks": [
    {
     "id": "t0140",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0133",
     "title": "Month review: Python, OOP, backend, SQL checklists",
     "hours": 2,
     "type": "review",
     "details": "",
     "link": ""
    },
    {
     "id": "t0147",
     "title": "Beyond the Basics, video 23 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-10",
   "week": 6,
   "tasks": [
    {
     "id": "t0141",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0134",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0148",
     "title": "System Design playlist, video 18 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-11",
   "week": 6,
   "tasks": [
    {
     "id": "t0142",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0135",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0149",
     "title": "Beyond the Basics, video 24 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-12",
   "week": 7,
   "tasks": [
    {
     "id": "t0166",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0150",
     "title": "NLP basics + text preprocessing (keep it short)",
     "hours": 1.5,
     "type": "study",
     "details": "Normalization, sentence/word splitting, n-grams, vocabulary, OOV.",
     "link": ""
    },
    {
     "id": "t0179",
     "title": "Beyond the Basics, video 25 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-13",
   "week": 7,
   "tasks": [
    {
     "id": "t0167",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0151",
     "title": "Tokenization: BPE, WordPiece, special tokens, context window",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0152",
     "title": "Practice: tokenizer on English, Arabic, Egyptian Arabic, code",
     "hours": 1.5,
     "type": "project",
     "details": "Compare token counts; note anything useful for Kalamna.",
     "link": "https://huggingface.co/learn/llm-course"
    },
    {
     "id": "t0180",
     "title": "System Design playlist, video 19 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-14",
   "week": 7,
   "tasks": [
    {
     "id": "t0168",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0153",
     "title": "Embeddings: vectors, cosine / dot / euclidean, top-k",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0154",
     "title": "Practice: documents → embeddings → top-k retrieval",
     "hours": 2,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0181",
     "title": "Beyond the Basics, video 26 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-15",
   "week": 7,
   "tasks": [
    {
     "id": "t0169",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0155",
     "title": "Cosmic Python ch. 6: Unit of Work",
     "hours": 2.5,
     "type": "book",
     "details": "",
     "link": "https://www.cosmicpython.com/book/preface.html"
    },
    {
     "id": "t0182",
     "title": "System Design playlist, video 20 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-16",
   "week": 7,
   "tasks": [
    {
     "id": "t0170",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0156",
     "title": "Neural networks → attention (conceptual, 3Blue1Brown)",
     "hours": 3,
     "type": "study",
     "details": "Forward pass, loss, backprop, RNN/LSTM limits, Q/K/V.",
     "link": "https://www.youtube.com/@3blue1brown"
    },
    {
     "id": "t0183",
     "title": "Beyond the Basics, video 27 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-17",
   "week": 7,
   "tasks": [
    {
     "id": "t0171",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0162",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    },
    {
     "id": "t0184",
     "title": "System Design playlist, video 21 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-18",
   "week": 7,
   "tasks": [
    {
     "id": "t0172",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0157",
     "title": "Transformers: self-attention, multi-head, positional info, encoder/decoder",
     "hours": 3,
     "type": "study",
     "details": "BERT vs GPT vs T5.",
     "link": "https://jalammar.github.io/illustrated-transformer/"
    },
    {
     "id": "t0158",
     "title": "Hugging Face: pipeline, tokenizers, generation params",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": "https://huggingface.co/learn/llm-course"
    },
    {
     "id": "t0185",
     "title": "Beyond the Basics, video 28 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-19",
   "week": 7,
   "tasks": [
    {
     "id": "t0173",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0159",
     "title": "Practice: sentiment, generation, embeddings, QA with transformers",
     "hours": 2,
     "type": "project",
     "details": "",
     "link": ""
    },
    {
     "id": "t0186",
     "title": "System Design playlist, video 22 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-20",
   "week": 7,
   "tasks": [
    {
     "id": "t0174",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0160",
     "title": "Cosmic Python ch. 7: Aggregates and Consistency Boundaries",
     "hours": 2.5,
     "type": "book",
     "details": "",
     "link": "https://www.cosmicpython.com/book/preface.html"
    },
    {
     "id": "t0187",
     "title": "System Design playlist, video 23 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-21",
   "week": 7,
   "tasks": [
    {
     "id": "t0175",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0161",
     "title": "Project: Semantic Search Engine",
     "hours": 4,
     "type": "project",
     "details": "embed_documents, embed_query, similarity, retrieve(query, k).",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-11-22",
   "week": 7,
   "tasks": [
    {
     "id": "t0176",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0163",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-11-23",
   "week": 7,
   "tasks": [
    {
     "id": "t0177",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0164",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-11-24",
   "week": 7,
   "tasks": [
    {
     "id": "t0178",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0165",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-11-25",
   "week": 8,
   "tasks": [
    {
     "id": "t0197",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0188",
     "title": "What is an LLM: next-token prediction, autoregressive generation, context window",
     "hours": 2.5,
     "type": "study",
     "details": "Optional: Karpathy's 'Deep Dive into LLMs like ChatGPT'.",
     "link": "https://www.youtube.com/@AndrejKarpathy"
    },
    {
     "id": "t0206",
     "title": "Beyond the Basics, video 29 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-26",
   "week": 8,
   "tasks": [
    {
     "id": "t0198",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0189",
     "title": "How LLMs are trained: cross-entropy, gradient descent, batch/lr, overfitting",
     "hours": 3.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0207",
     "title": "System Design playlist, video 24 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-27",
   "week": 8,
   "tasks": [
    {
     "id": "t0199",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0190",
     "title": "Decoder-only architecture review: causal mask, logits, softmax",
     "hours": 2.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0208",
     "title": "Beyond the Basics, video 30 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-28",
   "week": 8,
   "tasks": [
    {
     "id": "t0200",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0191",
     "title": "Decoding: greedy, sampling, temperature, top-k, top-p, stop sequences",
     "hours": 2.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0209",
     "title": "System Design playlist, video 25 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-11-29",
   "week": 8,
   "tasks": [
    {
     "id": "t0201",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0192",
     "title": "Base → chat model: instruction tuning, RLHF, DPO, chat templates",
     "hours": 2.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0210",
     "title": "Beyond the Basics, video 31 of 31",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video; 1.25x speed works well.",
     "link": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q"
    }
   ]
  },
  {
   "date": "2026-11-30",
   "week": 8,
   "tasks": [
    {
     "id": "t0202",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0193",
     "title": "LLM APIs: streaming, retries, timeouts, rate limits, token cost",
     "hours": 3.5,
     "type": "project",
     "details": "Reuse your Week 2–3 provider code for the LLM service layer.",
     "link": ""
    },
    {
     "id": "t0211",
     "title": "System Design playlist, video 26 of 26",
     "hours": 0.33,
     "type": "video",
     "details": "One ~20 min video.",
     "link": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX"
    }
   ]
  },
  {
   "date": "2026-12-01",
   "week": 8,
   "tasks": [
    {
     "id": "t0203",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0194",
     "title": "LLM evaluation basics: factuality, hallucination, latency, cost",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-02",
   "week": 8,
   "tasks": [
    {
     "id": "t0204",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0195",
     "title": "Project: LLM Q&A API with token/latency/cost logging",
     "hours": 3,
     "type": "project",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-03",
   "week": 8,
   "tasks": [
    {
     "id": "t0205",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0196",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-04",
   "week": 9,
   "tasks": [
    {
     "id": "t0219",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0212",
     "title": "Prompt fundamentals: instruction vs context vs input, delimiters, few-shot",
     "hours": 3,
     "type": "study",
     "details": "Write a bad → improved → structured → few-shot prompt for one task.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-05",
   "week": 9,
   "tasks": [
    {
     "id": "t0220",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0213",
     "title": "Advanced prompting + templates (classification, extraction, summarization, JSON)",
     "hours": 3.5,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-06",
   "week": 9,
   "tasks": [
    {
     "id": "t0221",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0214",
     "title": "Agent book ch. 1: What is an AI agent?",
     "hours": 2,
     "type": "book",
     "details": "",
     "link": "https://www.manning.com/books/build-an-ai-agent-from-scratch"
    }
   ]
  },
  {
   "date": "2026-12-07",
   "week": 9,
   "tasks": [
    {
     "id": "t0222",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0215",
     "title": "Structured output: JSON Schema, Pydantic validation, retry on invalid output",
     "hours": 4,
     "type": "project",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-08",
   "week": 9,
   "tasks": [
    {
     "id": "t0223",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0218",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-09",
   "week": 9,
   "tasks": [
    {
     "id": "t0224",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0216",
     "title": "Agent book ch. 2: The brain of AI agents: LLMs",
     "hours": 2,
     "type": "book",
     "details": "",
     "link": "https://www.manning.com/books/build-an-ai-agent-from-scratch"
    }
   ]
  },
  {
   "date": "2026-12-10",
   "week": 9,
   "tasks": [
    {
     "id": "t0225",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0217",
     "title": "Failure modes + prompt injection, untrusted retrieved content",
     "hours": 3,
     "type": "study",
     "details": "Relevant to Kalamna: customer documents are untrusted data.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-11",
   "week": 10,
   "tasks": [
    {
     "id": "t0241",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0226",
     "title": "RAG architecture deep dive: offline indexing vs online query, IDs, citations",
     "hours": 3,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-12",
   "week": 10,
   "tasks": [
    {
     "id": "t0242",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0227",
     "title": "Types of RAG: naive, advanced, modular, hybrid, multi-query, parent-child, hierarchical, GraphRAG",
     "hours": 4,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-13",
   "week": 10,
   "tasks": [
    {
     "id": "t0243",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0237",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-14",
   "week": 10,
   "tasks": [
    {
     "id": "t0244",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0228",
     "title": "Vector databases: dedicated, pgvector, search engines, FAISS",
     "hours": 3,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-15",
   "week": 10,
   "tasks": [
    {
     "id": "t0245",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0229",
     "title": "Vector search + ANN: HNSW, IVF, PQ, speed vs recall vs memory",
     "hours": 3,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-16",
   "week": 10,
   "tasks": [
    {
     "id": "t0246",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0230",
     "title": "Retrieval: dense, BM25, hybrid, RRF, reranking",
     "hours": 4,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-17",
   "week": 10,
   "tasks": [
    {
     "id": "t0247",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0238",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-18",
   "week": 10,
   "tasks": [
    {
     "id": "t0248",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0231",
     "title": "RAG evaluation: Recall/Precision@K, MRR, NDCG, faithfulness, abstention",
     "hours": 3.5,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0232",
     "title": "Research case: RAG evaluation (write-up)",
     "hours": 1.5,
     "type": "research",
     "details": "Fill the case in Research cases.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-19",
   "week": 10,
   "tasks": [
    {
     "id": "t0249",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0233",
     "title": "Production RAG: P50/P95/P99, TTFT, cost, multi-tenancy, failure handling",
     "hours": 2.5,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-20",
   "week": 10,
   "tasks": [
    {
     "id": "t0250",
     "title": "Kalamna work block (project week)",
     "hours": 2,
     "type": "kalamna",
     "details": "Build the Production-style RAG project inside Kalamna (hybrid + RRF + reranker + citations + metrics)",
     "link": ""
    },
    {
     "id": "t0234",
     "title": "Capacity & scaling: Little's Law, prefill vs decode, KV-cache, GPU sizing",
     "hours": 3,
     "type": "study",
     "details": "Work through the 4,000 users / 100 concurrent / P95 < 8s assignment.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-21",
   "week": 10,
   "tasks": [
    {
     "id": "t0251",
     "title": "Kalamna work block (project week)",
     "hours": 2,
     "type": "kalamna",
     "details": "Build the Production-style RAG project inside Kalamna (hybrid + RRF + reranker + citations + metrics)",
     "link": ""
    },
    {
     "id": "t0235",
     "title": "Research case: From demo to production (write-up)",
     "hours": 1,
     "type": "research",
     "details": "",
     "link": ""
    },
    {
     "id": "t0236",
     "title": "Research case: Multi-user, multi-channel conversations (write-up)",
     "hours": 1.5,
     "type": "research",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-22",
   "week": 10,
   "tasks": [
    {
     "id": "t0252",
     "title": "Kalamna work block (project week)",
     "hours": 2,
     "type": "kalamna",
     "details": "Build the Production-style RAG project inside Kalamna (hybrid + RRF + reranker + citations + metrics)",
     "link": ""
    },
    {
     "id": "t0239",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-23",
   "week": 10,
   "tasks": [
    {
     "id": "t0253",
     "title": "Kalamna work block (project week)",
     "hours": 2,
     "type": "kalamna",
     "details": "Build the Production-style RAG project inside Kalamna (hybrid + RRF + reranker + citations + metrics)",
     "link": ""
    },
    {
     "id": "t0240",
     "title": "Catch-up / review day",
     "hours": 2.5,
     "type": "review",
     "details": "Finish anything unchecked from this week, or revise the checklist.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-24",
   "week": 11,
   "tasks": [
    {
     "id": "t0264",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0254",
     "title": "Agent fundamentals: goal, state, actions, observations, loop (quick review after ch. 1)",
     "hours": 1,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0255",
     "title": "Agent book ch. 3: Enabling actions: tool use",
     "hours": 3,
     "type": "book",
     "details": "",
     "link": "https://www.manning.com/books/build-an-ai-agent-from-scratch"
    }
   ]
  },
  {
   "date": "2026-12-25",
   "week": 11,
   "tasks": [
    {
     "id": "t0265",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0256",
     "title": "Agent loop + ReAct, termination, max iterations",
     "hours": 1.5,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-26",
   "week": 11,
   "tasks": [
    {
     "id": "t0266",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0257",
     "title": "Tools: schemas, validation, errors, retries, timeouts",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-27",
   "week": 11,
   "tasks": [
    {
     "id": "t0267",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0258",
     "title": "Agent book ch. 4: Implementing a basic ReAct agent",
     "hours": 3,
     "type": "book",
     "details": "",
     "link": "https://www.manning.com/books/build-an-ai-agent-from-scratch"
    }
   ]
  },
  {
   "date": "2026-12-28",
   "week": 11,
   "tasks": [
    {
     "id": "t0268",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0259",
     "title": "Architectures: ReAct, planner–executor, reflection; workflow vs agent",
     "hours": 3,
     "type": "research",
     "details": "Together with Agent guide 1A.",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-29",
   "week": 11,
   "tasks": [
    {
     "id": "t0269",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0260",
     "title": "Agent state vs memory basics",
     "hours": 1,
     "type": "study",
     "details": "",
     "link": ""
    },
    {
     "id": "t0261",
     "title": "Reliability: loops, fallbacks, escalation, autonomy slider",
     "hours": 2,
     "type": "study",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-30",
   "week": 11,
   "tasks": [
    {
     "id": "t0270",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0262",
     "title": "Research case: Tool design, selection & execution (write-up)",
     "hours": 1.5,
     "type": "research",
     "details": "",
     "link": ""
    }
   ]
  },
  {
   "date": "2026-12-31",
   "week": 11,
   "tasks": [
    {
     "id": "t0271",
     "title": "Kalamna work block",
     "hours": 2,
     "type": "kalamna",
     "details": "",
     "link": ""
    },
    {
     "id": "t0263",
     "title": "Project: Single-agent Research Assistant (extend the book's ReAct agent)",
     "hours": 3.5,
     "type": "project",
     "details": "Tool schemas, loop, state, max iterations, error handling, logging.",
     "link": ""
    }
   ]
  }
 ],
 "cases": [
  {
   "id": "rag-eval",
   "source": "RAG guide",
   "title": "RAG evaluation: how do we know it actually works?",
   "week": 10,
   "question": "If we built a RAG system tomorrow, what exact metrics and evaluation process would we put in place?"
  },
  {
   "id": "rag-capacity",
   "source": "RAG guide",
   "title": "From demo to production: capacity, scaling & infrastructure",
   "week": 10,
   "question": "4,000 users, 100 concurrent, 20K input / 500 output tokens, P95 < 8s: are 1, 2, 4, 8 or 16 GPUs enough?"
  },
  {
   "id": "rag-multiuser",
   "source": "RAG guide",
   "title": "Multi-user, multi-channel conversations",
   "week": 10,
   "question": "How would you design identity + sessions + history + memory for a multi-channel enterprise RAG app?"
  },
  {
   "id": "agent-1a",
   "source": "Agent guide",
   "title": "Agent techniques & architectures (1A)",
   "week": 11,
   "question": "Pick one default agent technique for an enterprise internal assistant. Which, and why?"
  },
  {
   "id": "agent-1b",
   "source": "Agent guide",
   "title": "Tool design, selection & execution (1B)",
   "week": 11,
   "question": "Design a minimal but production-ready tool layer for an agent that searches documents, calls internal APIs, and writes to a database."
  },
  {
   "id": "agent-2a",
   "source": "Agent guide",
   "title": "Multi-agent architectures & coordination (2A)",
   "week": null,
   "question": "Research, write a report, fact-check it: one agent with tools, manager + specialists, or another pattern?"
  },
  {
   "id": "agent-2b",
   "source": "Agent guide",
   "title": "Knowledge, memory & state management (2B)",
   "week": null,
   "question": "Design a memory architecture for a multi-agent customer-support system without leaking data across customers or agents."
  },
  {
   "id": "agent-3a",
   "source": "Agent guide",
   "title": "Evaluation, measurement & monitoring (3A)",
   "week": null,
   "question": "If we launch an agent system next month, what evaluation + monitoring stack would you put in place on day 1?"
  },
  {
   "id": "agent-3b",
   "source": "Agent guide",
   "title": "Security, reliability & human collaboration (3B)",
   "week": null,
   "question": "Design the safety + human oversight layer for an agent that reads company data and sends emails for users."
  }
 ],
 "guide": [
  {
   "week": 1,
   "goal": "Write clean, modern Python and understand how it works underneath.",
   "sections": [
    [
     "Fundamentals",
     [
      "Data types and collections: list, tuple, set, dict",
      "Mutable vs immutable",
      "Why dict keys must be hashable",
      "== vs is",
      "Shallow vs deep copy",
      "What happens when you pass a list to a function"
     ]
    ],
    [
     "Functions",
     [
      "Functions and scope",
      "*args and **kwargs",
      "Lambda",
      "map and filter",
      "List and dict comprehensions (and when they're better)"
     ]
    ],
    [
     "Python internals",
     [
      "Iterable vs iterator",
      "Generators and yield",
      "Decorators",
      "Context managers: __enter__ / __exit__",
      "Exceptions: try / except / else / finally, custom exceptions"
     ]
    ],
    [
     "Code organization",
     [
      "Modules vs packages, __init__.py",
      "Absolute vs relative imports",
      "Virtual environments",
      "Type hints",
      "Dataclasses",
      "Pydantic, and dataclass vs Pydantic"
     ]
    ],
    [
     "Concurrency",
     [
      "async / await and the event loop",
      "asyncio.gather",
      "Threads vs processes",
      "CPU-bound vs I/O-bound",
      "Why async doesn't speed up CPU-heavy code"
     ]
    ]
   ]
  },
  {
   "week": 2,
   "goal": "Go from OOP syntax to designing maintainable components.",
   "sections": [
    [
     "OOP fundamentals",
     [
      "Class, object, instance, self, __init__",
      "Instance vs class attributes",
      "Instance, class and static methods",
      "Constructor vs factory method"
     ]
    ],
    [
     "Four pillars",
     [
      "Encapsulation: public, _protected, __private, properties",
      "Inheritance: super(), multiple inheritance, MRO",
      "Polymorphism",
      "Abstraction with ABC"
     ]
    ],
    [
     "Relationships",
     [
      "IS-A vs HAS-A",
      "Composition, aggregation, association",
      "Why composition often beats deep inheritance"
     ]
    ],
    [
     "Advanced Python OOP",
     [
      "Dunder methods: __str__, __repr__, __eq__, __hash__, __len__, __getitem__, __iter__",
      "__eq__, __hash__ and immutability",
      "Properties: getter, setter, deleter",
      "Dataclasses: frozen, defaults, field()",
      "Protocol vs ABC",
      "Dependency injection"
     ]
    ],
    [
     "SOLID",
     [
      "Single responsibility",
      "Open/closed",
      "Liskov substitution",
      "Interface segregation",
      "Dependency inversion"
     ]
    ],
    [
     "Design patterns (first pass)",
     [
      "Factory, Factory Method, Builder",
      "Adapter, Decorator, Facade",
      "Strategy, Observer",
      "Repository and service layer"
     ]
    ],
    [
     "Book",
     [
      "Cosmic Python ch. 1: Domain modeling",
      "Cosmic Python ch. 2: Repository pattern"
     ]
    ]
   ]
  },
  {
   "week": 3,
   "goal": "Production architecture, clean code, and the core of backend engineering.",
   "sections": [
    [
     "Production OOP",
     [
      "Layers: API, service, domain, infrastructure",
      "OOP in Django: Model, Manager, QuerySet, Serializer, View, Permission, Middleware",
      "OOP in FastAPI: Depends, services, repositories",
      "OOP in AI: LLMProvider, Retriever, VectorStore, Memory abstractions",
      "Testing with fakes (FakeLLM, FakeRetriever)"
     ]
    ],
    [
     "Clean code",
     [
      "Naming",
      "Small, single-purpose functions; side effects",
      "Cohesion and coupling, avoiding god classes",
      "Guard clauses instead of nested ifs",
      "DRY (and not abstracting too early), KISS, YAGNI"
     ]
    ],
    [
     "Git",
     [
      "Working tree → staging → commit → remote",
      "Branch, merge, rebase, conflicts",
      "stash, reset vs revert, cherry-pick",
      "fetch vs pull, HEAD, origin",
      "Pull request workflow, .gitignore, commit messages"
     ]
    ],
    [
     "HTTP, JSON, REST",
     [
      "Methods, headers, path and query params, body",
      "Status codes (2xx, 4xx, 5xx)",
      "Statelessness, idempotency, caching, cookies",
      "Resource URLs, pagination, filtering, sorting, versioning",
      "Error responses",
      "JSON serialization and deserialization"
     ]
    ],
    [
     "Authentication & authorization",
     [
      "AuthN vs AuthZ",
      "Password hashing: salt, bcrypt, Argon2",
      "Sessions vs JWT; access and refresh tokens",
      "Expiration, rotation, revocation limits",
      "RBAC, permissions, object-level authorization",
      "401 vs 403"
     ]
    ],
    [
     "Book",
     [
      "Cosmic Python ch. 3: Coupling and abstractions"
     ]
    ]
   ]
  },
  {
   "week": 4,
   "goal": "Make the backend testable, observable and configurable.",
   "sections": [
    [
     "Testing",
     [
      "Testing pyramid: unit, integration, E2E",
      "pytest, fixtures, parametrize, markers",
      "Mocking (and mocking LLMs)",
      "API tests for success and failure paths (401, 403, 404, 409, 422)"
     ]
    ],
    [
     "Logging & configuration",
     [
      "Log levels",
      "Structured logs, request and correlation IDs",
      "What never to log: passwords, tokens, keys",
      "Environment variables, .env, secrets",
      "Pydantic Settings; dev / test / staging / prod"
     ]
    ],
    [
     "Design patterns (problem → pattern → trade-off)",
     [
      "Factory",
      "Strategy",
      "Adapter",
      "Decorator",
      "Facade",
      "Observer",
      "Repository",
      "Dependency injection"
     ]
    ],
    [
     "Capstone (in Kalamna hours)",
     [
      "Production-style AI support API: auth, validation, providers, retrieval, logging, tests"
     ]
    ],
    [
     "Book",
     [
      "Cosmic Python ch. 4: Service layer"
     ]
    ]
   ]
  },
  {
   "week": 5,
   "goal": "Write intermediate SQL confidently without an ORM.",
   "sections": [
    [
     "SQL foundations",
     [
      "Tables, rows, primary / foreign / candidate keys, NULL",
      "PostgreSQL data types",
      "SELECT, WHERE, IN, BETWEEN, LIKE / ILIKE, IS NULL",
      "ORDER BY, LIMIT, OFFSET, DISTINCT",
      "CASE"
     ]
    ],
    [
     "Database design",
     [
      "1:1, 1:N, N:M relationships",
      "Foreign keys and ON DELETE: cascade, restrict, set null",
      "Constraints: NOT NULL, UNIQUE, CHECK, DEFAULT",
      "Normalization 1NF–3NF and denormalization"
     ]
    ],
    [
     "Aggregation & joins",
     [
      "COUNT, SUM, AVG, MIN, MAX",
      "GROUP BY, HAVING vs WHERE",
      "INNER, LEFT, RIGHT, FULL, CROSS, SELF JOIN",
      "Why LEFT JOIN keeps users with zero orders"
     ]
    ],
    [
     "Advanced queries",
     [
      "Scalar and correlated subqueries",
      "IN vs EXISTS",
      "CTEs",
      "Window functions: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, SUM OVER",
      "GROUP BY vs window functions",
      "Dates: DATE_TRUNC, INTERVAL"
     ]
    ],
    [
     "Practice & extras",
     [
      "~20 LeetCode SQL problems",
      "Cosmic Python ch. 5: TDD in high and low gear",
      "System Design Course (2h)"
     ]
    ]
   ]
  },
  {
   "week": 6,
   "goal": "Use PostgreSQL well and connect SQL to the ORM.",
   "sections": [
    [
     "PostgreSQL",
     [
      "Schemas, roles, permissions, extensions",
      "UUID, JSONB, arrays, TIMESTAMP vs TIMESTAMPTZ",
      "SERIAL / identity columns",
      "RETURNING, ON CONFLICT (upsert)",
      "Transactions and ACID",
      "Isolation levels (Read Committed, Serializable)"
     ]
    ],
    [
     "Indexes & performance",
     [
      "B-tree indexes",
      "Composite indexes and column order",
      "When indexes hurt",
      "EXPLAIN and EXPLAIN ANALYZE",
      "Seq scan vs index scan vs bitmap scan"
     ]
    ],
    [
     "ORM bridge",
     [
      "filter, exclude, get, values",
      "annotate, aggregate, F, Q",
      "Exists, Subquery, OuterRef",
      "select_related vs prefetch_related",
      "N+1 problem; ORM vs raw SQL"
     ]
    ],
    [
     "Practice & extras",
     [
      "35 LeetCode SQL problems total, all 8 patterns",
      "1 Million Requests per Second video",
      "Month 1 review"
     ]
    ]
   ]
  },
  {
   "week": 7,
   "goal": "Understand the components under LLMs: tokens, embeddings, attention.",
   "sections": [
    [
     "Text processing",
     [
      "What NLP is",
      "Unicode normalization, cleaning",
      "Sentence and word splitting",
      "Stop words, stemming vs lemmatization",
      "N-grams, vocabulary, OOV"
     ]
    ],
    [
     "Tokenization",
     [
      "Token vs word vs character",
      "Token IDs, special tokens (BOS, EOS, PAD, UNK)",
      "BPE, WordPiece, Unigram",
      "Context window and token counting",
      "Why Arabic uses more tokens"
     ]
    ],
    [
     "Embeddings",
     [
      "What an embedding represents",
      "Dense vectors and dimensions",
      "Cosine similarity, dot product, Euclidean distance",
      "Normalization; similarity vs distance",
      "Top-k retrieval"
     ]
    ],
    [
     "Neural networks → attention",
     [
      "Layers, weights, activations",
      "Forward pass, loss, gradient, backpropagation",
      "Training vs inference",
      "RNN, LSTM and their limits",
      "Attention: query, key, value"
     ]
    ],
    [
     "Transformers",
     [
      "Self-attention, multi-head attention",
      "Feed-forward, residuals, layer norm",
      "Positional encoding",
      "Encoder, decoder, causal and cross-attention",
      "BERT vs GPT vs T5"
     ]
    ],
    [
     "Hugging Face & project",
     [
      "Models, tokenizers, pipeline()",
      "Generation: max_new_tokens, temperature, top_k, top_p",
      "Architecture vs weights vs tokenizer vs inference",
      "Semantic search engine project"
     ]
    ],
    [
     "Book",
     [
      "Cosmic Python ch. 6: Unit of work",
      "Cosmic Python ch. 7: Aggregates"
     ]
    ]
   ]
  },
  {
   "week": 8,
   "goal": "Know how LLMs are trained, how they generate, and how to call them in production.",
   "sections": [
    [
     "LLM fundamentals",
     [
      "Language model vs LLM vs chatbot",
      "Next-token prediction, autoregressive generation",
      "Parameters, weights, model size",
      "Context window; training vs inference vs serving"
     ]
    ],
    [
     "Training",
     [
      "Dataset, tokenization, input/target shifting",
      "Cross-entropy loss, gradient descent",
      "Batch size, learning rate, epochs, steps",
      "Training vs validation loss, overfitting",
      "Why next-token prediction leads to useful capabilities"
     ]
    ],
    [
     "Architecture",
     [
      "Decoder-only transformer",
      "Causal mask",
      "Token embeddings + positional information",
      "Logits and softmax"
     ]
    ],
    [
     "Generation",
     [
      "Greedy vs sampling",
      "Temperature, top-k, top-p",
      "Stop sequences, max tokens, repetition penalty",
      "Top-k retrieval vs top-k generation"
     ]
    ],
    [
     "Base → chat model",
     [
      "Pretraining",
      "Instruction tuning",
      "RLHF, reward models, DPO",
      "Chat templates; system / user / assistant messages"
     ]
    ],
    [
     "Engineering",
     [
      "LLM APIs, auth, model selection",
      "Streaming, structured responses",
      "Retries, timeouts, rate limits",
      "Token counting and cost",
      "Provider abstraction layer",
      "Basic evaluation: factuality, hallucination, latency, cost"
     ]
    ]
   ]
  },
  {
   "week": 9,
   "goal": "Communicate tasks to models reliably and safely.",
   "sections": [
    [
     "Prompt fundamentals",
     [
      "Instruction vs context vs input vs output constraint",
      "System, user, assistant messages",
      "Delimiters, role prompting",
      "Zero-, one-, few-shot"
     ]
    ],
    [
     "Advanced prompting",
     [
      "Task decomposition",
      "Chain-of-thought and self-consistency (concepts)",
      "ReAct (concept)",
      "Prompt templates and dynamic prompts",
      "Prompt engineering vs RAG"
     ]
    ],
    [
     "Structured output",
     [
      "JSON and JSON Schema",
      "Pydantic validation, required vs optional, enums",
      "Parsing failures and retry / re-prompt"
     ]
    ],
    [
     "Reliability & security",
     [
      "Hallucination, ignored context, unsupported answers",
      "Prompt injection and indirect injection",
      "Retrieved content is untrusted data",
      "Instruction / data separation"
     ]
    ],
    [
     "Book",
     [
      "Agent book ch. 1: What is an AI agent?",
      "Agent book ch. 2: LLMs as the agent's brain"
     ]
    ]
   ]
  },
  {
   "week": 10,
   "goal": "Design, evaluate and run RAG as a production system.",
   "sections": [
    [
     "RAG architectures",
     [
      "Offline indexing vs online query pipeline",
      "Naive, advanced, modular RAG",
      "Hybrid, multi-query, query rewriting",
      "Parent-child, hierarchical RAG",
      "GraphRAG; agentic RAG (concept)",
      "Document IDs, chunk IDs, citations"
     ]
    ],
    [
     "Vector databases",
     [
      "What a vector DB stores (vectors + metadata)",
      "Dedicated DBs: Pinecone, Milvus, Qdrant, Weaviate",
      "PostgreSQL + pgvector",
      "Search engines with vector support",
      "FAISS / local indexes",
      "Exact search vs ANN: HNSW, IVF, product quantization"
     ]
    ],
    [
     "Retrieval",
     [
      "Chunking strategies and overlap",
      "Dense vs sparse (TF-IDF, BM25)",
      "Hybrid retrieval and RRF",
      "Reranking",
      "Metadata filtering, top-k"
     ]
    ],
    [
     "Evaluation",
     [
      "Recall@K, Precision@K, hit rate, MRR, NDCG",
      "Correctness, faithfulness, citation quality",
      "Hallucination rate, abstention",
      "Retrieval quality vs answer quality"
     ]
    ],
    [
     "Production",
     [
      "P50 / P95 / P99, TTFT, throughput",
      "Cost per request",
      "Capacity: Little's Law, prefill vs decode, KV-cache",
      "Multi-tenancy and data isolation",
      "Empty retrieval and failure handling"
     ]
    ],
    [
     "Research cases (RAG guide)",
     [
      "RAG evaluation",
      "From demo to production",
      "Multi-user, multi-channel conversations"
     ]
    ]
   ]
  },
  {
   "week": 11,
   "goal": "Build a reliable single-agent system.",
   "sections": [
    [
     "Agent fundamentals",
     [
      "LLM app vs agent",
      "Goal, state, environment, actions, observations",
      "The agent loop, autonomy"
     ]
    ],
    [
     "Techniques",
     [
      "ReAct",
      "Planner–executor",
      "Reflection / Reflexion",
      "Query decomposition",
      "Reactive vs goal-directed agents",
      "When a fixed workflow beats an agent"
     ]
    ],
    [
     "Tools",
     [
      "Tool schemas, inputs, outputs, descriptions",
      "Tool selection and validation",
      "Errors, retries, timeouts",
      "Tool design and permissions"
     ]
    ],
    [
     "State & reliability",
     [
      "Agent state vs memory",
      "Max iterations, infinite loops",
      "Fallbacks and graceful failure",
      "Human escalation, autonomy slider"
     ]
    ],
    [
     "Practice",
     [
      "Agent book ch. 3: Tool use",
      "Agent book ch. 4: Basic ReAct agent",
      "Single-agent research assistant project",
      "Research cases: Agent guide 1A and 1B"
     ]
    ]
   ]
  }
 ],
 "next_plan": {
  "title": "Next 3 months (Jan – Mar 2027)",
  "intro": "The next plan continues the same flow: fundamentals → LLMs → RAG → agents → production AI systems. It picks up exactly where Week 11 ends. Details will be planned later.",
  "sections": [
   [
    "Multi-agent systems",
    [
     "Single vs multi-agent, avoiding agent sprawl",
     "Manager/worker, hierarchical, democratic, swarm, actor-critic",
     "Communication: shared state, message brokers, event buses, A2A",
     "Orchestration engines and frameworks (LangGraph, AutoGen, CrewAI)"
    ]
   ],
   [
    "Agent memory",
    [
     "Context vs state vs memory",
     "Short-term and long-term memory",
     "Semantic, episodic, procedural memory",
     "Memory lifecycle: capture, store, retrieve, consolidate, expire",
     "Privacy and tenant isolation"
    ]
   ],
   [
    "Production agents",
    [
     "Evaluation of agent trajectories",
     "Monitoring and observability (traces, OpenTelemetry, Langfuse)",
     "Security: tool misuse, injection, threat modeling",
     "Reliability and human oversight"
    ]
   ],
   [
    "Books & research",
    [
     "Agent book Part 2: RAG knowledge bases, memory, planning, code execution, multi-agent, evaluation",
     "Agent guide cases 2A, 2B, 3A, 3B"
    ]
   ],
   [
    "Also on the list",
    [
     "Side project",
     "Remaining backend stack from the roadmap: Django/DRF, FastAPI, Redis, Docker"
    ]
   ]
  ]
 },
 "materials": [
  {
   "id": "m-btb",
   "title": "Beyond the Basics (ما بعد الأساسيات), pragma",
   "kind": "Playlist",
   "url": "https://www.youtube.com/playlist?list=PL9ExMy1CBZjnsv2WXFKxXNf41iT1pdT2Q",
   "weeks": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8
   ],
   "note": "31 videos, about 4 per week through Week 8.",
   "source": "plan"
  },
  {
   "id": "m-sd",
   "title": "System Design playlist",
   "kind": "Playlist",
   "url": "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX",
   "weeks": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8
   ],
   "note": "26 videos of 15–25 min. Check this link: it may point to the wrong playlist.",
   "source": "plan"
  },
  {
   "id": "m-sdc",
   "title": "System Design Course: APIs, Databases, Caching, CDNs, Load Balancing",
   "kind": "Video",
   "url": "https://youtu.be/oYxTTirKY8M",
   "weeks": [
    5
   ],
   "note": "2h, split into two sessions.",
   "source": "plan"
  },
  {
   "id": "m-rps",
   "title": "Let's Handle 1 Million Requests per Second",
   "kind": "Video",
   "url": "https://youtu.be/W4EwfEU8CGA",
   "weeks": [
    6
   ],
   "note": "2h 30m, Month 1 finale.",
   "source": "plan"
  },
  {
   "id": "m-cosmic",
   "title": "Architecture Patterns with Python (Cosmic Python)",
   "kind": "Book",
   "url": "https://www.cosmicpython.com/book/preface.html",
   "weeks": [
    2,
    3,
    4,
    5,
    7
   ],
   "note": "Free online. Part 1 (ch. 1–7) in this plan.",
   "source": "plan"
  },
  {
   "id": "m-agentbook",
   "title": "Build an AI Agent (From Scratch), Hur & Song",
   "kind": "Book",
   "url": "https://www.manning.com/books/build-an-ai-agent-from-scratch",
   "weeks": [
    9,
    11
   ],
   "note": "Part 1 (ch. 1–4) in this plan; Part 2 next plan.",
   "source": "plan"
  },
  {
   "id": "m-lc",
   "title": "LeetCode: Top SQL 50",
   "kind": "Practice",
   "url": "https://leetcode.com/studyplan/top-sql-50/",
   "weeks": [
    5,
    6
   ],
   "note": "35 problems across the 8 SQL patterns.",
   "source": "plan"
  },
  {
   "id": "m-ragguide",
   "title": "BARQ RAG research guide (PDF)",
   "kind": "Guide",
   "url": "",
   "weeks": [
    10
   ],
   "note": "Your internship PDF. Answer the cases in Research cases.",
   "source": "plan"
  },
  {
   "id": "m-agentguide",
   "title": "BARQ Agent research guide (PDF)",
   "kind": "Guide",
   "url": "",
   "weeks": [
    11
   ],
   "note": "Your internship PDF. 1A and 1B in this plan; the rest next plan.",
   "source": "plan"
  },
  {
   "id": "s-pytut",
   "title": "Python tutorial (official docs)",
   "kind": "Docs",
   "url": "https://docs.python.org/3/tutorial/",
   "weeks": [
    1
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-asyncio",
   "title": "asyncio documentation",
   "kind": "Docs",
   "url": "https://docs.python.org/3/library/asyncio.html",
   "weeks": [
    1
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-pydantic",
   "title": "Pydantic documentation",
   "kind": "Docs",
   "url": "https://docs.pydantic.dev/latest/",
   "weeks": [
    1,
    9
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-datamodel",
   "title": "Python data model (dunder methods)",
   "kind": "Docs",
   "url": "https://docs.python.org/3/reference/datamodel.html",
   "weeks": [
    2
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-guru",
   "title": "Refactoring.Guru: design patterns (with Python examples)",
   "kind": "Website",
   "url": "https://refactoring.guru/design-patterns",
   "weeks": [
    2,
    4
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-progit",
   "title": "Pro Git book",
   "kind": "Book",
   "url": "https://git-scm.com/book/en/v2",
   "weeks": [
    3
   ],
   "note": "Free online.",
   "source": "suggested"
  },
  {
   "id": "s-mdnhttp",
   "title": "MDN: HTTP",
   "kind": "Docs",
   "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP",
   "weeks": [
    3
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-fastapi",
   "title": "FastAPI tutorial (incl. security / JWT)",
   "kind": "Docs",
   "url": "https://fastapi.tiangolo.com/tutorial/",
   "weeks": [
    3,
    4
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-owasp-pw",
   "title": "OWASP Password Storage Cheat Sheet",
   "kind": "Docs",
   "url": "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html",
   "weeks": [
    3
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-pytest",
   "title": "pytest documentation",
   "kind": "Docs",
   "url": "https://docs.pytest.org/",
   "weeks": [
    4
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-logging",
   "title": "Python logging HOWTO",
   "kind": "Docs",
   "url": "https://docs.python.org/3/howto/logging.html",
   "weeks": [
    4
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-settings",
   "title": "Pydantic Settings",
   "kind": "Docs",
   "url": "https://docs.pydantic.dev/latest/concepts/pydantic_settings/",
   "weeks": [
    4
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-pgtut",
   "title": "PostgreSQL tutorial (official docs)",
   "kind": "Docs",
   "url": "https://www.postgresql.org/docs/current/tutorial.html",
   "weeks": [
    5
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-pgwin",
   "title": "PostgreSQL: window functions",
   "kind": "Docs",
   "url": "https://www.postgresql.org/docs/current/tutorial-window.html",
   "weeks": [
    5
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-luke",
   "title": "Use The Index, Luke (SQL indexing)",
   "kind": "Website",
   "url": "https://use-the-index-luke.com/",
   "weeks": [
    6
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-explain",
   "title": "PostgreSQL: using EXPLAIN",
   "kind": "Docs",
   "url": "https://www.postgresql.org/docs/current/using-explain.html",
   "weeks": [
    6
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-djorm",
   "title": "Django: making queries",
   "kind": "Docs",
   "url": "https://docs.djangoproject.com/en/stable/topics/db/queries/",
   "weeks": [
    6
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-3b1b",
   "title": "3Blue1Brown: neural networks & transformers",
   "kind": "Playlist",
   "url": "https://www.youtube.com/@3blue1brown",
   "weeks": [
    7
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-illustrated",
   "title": "The Illustrated Transformer, Jay Alammar",
   "kind": "Article",
   "url": "https://jalammar.github.io/illustrated-transformer/",
   "weeks": [
    7
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-hf",
   "title": "Hugging Face LLM course",
   "kind": "Course",
   "url": "https://huggingface.co/learn/llm-course",
   "weeks": [
    7,
    8
   ],
   "note": "Chapters 1–2 fit Week 7.",
   "source": "suggested"
  },
  {
   "id": "s-tiktok",
   "title": "Tiktokenizer (see tokens live)",
   "kind": "Tool",
   "url": "https://tiktokenizer.vercel.app/",
   "weeks": [
    7
   ],
   "note": "Try Arabic vs English.",
   "source": "suggested"
  },
  {
   "id": "s-karpathy",
   "title": "Andrej Karpathy: Deep Dive into LLMs like ChatGPT",
   "kind": "Video",
   "url": "https://www.youtube.com/@AndrejKarpathy",
   "weeks": [
    8
   ],
   "note": "On his channel.",
   "source": "suggested"
  },
  {
   "id": "s-prompt",
   "title": "Anthropic prompt engineering guide",
   "kind": "Docs",
   "url": "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview",
   "weeks": [
    9
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-owasp-llm",
   "title": "OWASP Top 10 for LLM applications",
   "kind": "Docs",
   "url": "https://genai.owasp.org/llm-top-10/",
   "weeks": [
    9,
    10
   ],
   "note": "Prompt injection and related risks.",
   "source": "suggested"
  },
  {
   "id": "s-pgvector",
   "title": "pgvector",
   "kind": "Docs",
   "url": "https://github.com/pgvector/pgvector",
   "weeks": [
    10
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-react",
   "title": "ReAct paper (Yao et al.)",
   "kind": "Paper",
   "url": "https://arxiv.org/abs/2210.03629",
   "weeks": [
    11
   ],
   "note": "",
   "source": "suggested"
  },
  {
   "id": "s-effective",
   "title": "Building effective agents (Anthropic)",
   "kind": "Article",
   "url": "https://www.anthropic.com/engineering/building-effective-agents",
   "weeks": [
    11
   ],
   "note": "When to use workflows vs agents.",
   "source": "suggested"
  },
  {
   "id": "s-mcp",
   "title": "Model Context Protocol docs",
   "kind": "Docs",
   "url": "https://modelcontextprotocol.io/",
   "weeks": [
    11
   ],
   "note": "",
   "source": "suggested"
  }
 ]
};
